logging:
  level:
    org:
      springframework:
        security: debug
app:
  jwt-expiration-milliseconds: '604800000'
  jwt-secret: jwtsecretkey
spring:
  application:
    name: blogapp
  datasource:
    username: hdurmaz
    url: jdbc:postgresql://localhost:5432/blogapp
    password: hdurmaz
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true