spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id : BLOGAPP
          uri: lb://BLOGAPP
          predicates:
            - Path=/api/v1/**

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true